### PR TITLE
Modify Hero Section, Navbar and Add Standard file tree to the Project, also update README.md with screenshots

### PR DESCRIPTION
**Pull request by GayanKod**
This website can be more and more professional. I've done the landing page/hero section. And modify the navigation bar. 
Also, I beautify the .css files.
And Add standard file tree structure to this web project.
I did not change any file names or class names.
Also, I update the README.md file with  Screenshots of the project to get more attraction of contributors and reach more to the contributors. And It will be easy for contributors who visit this repository and see what they can do for this website to improve. 
Hope after this more contributors fork this and give their contributions to this repository!

### CODE REVIEW

**Comment by IAmSalvaMartini** [comment]
> This website can be more and more professional. I've done the landing page/hero section. And modify the navigation bar. Also, I beautify the .css files. And Add standard file tree structure to this web project. I did not change any file names or class names. Also, I update the README.md file with Screenshots of the project to get more attraction of contributors and reach more to the contributors. And It will be easy for contributors who visit this repository and see what they can do for this website to improve. Hope after this more contributors fork this and give their contributions to this repository!

I'll look into this tomorrow morning and then approve it

**Comment by IAmSalvaMartini** [comment]
In 506b5629cf0c0d7197e5c54a438578a34a4da325, please change all /public/subfolder/ to just subfolder/  eg: ```<link rel="stylesheet" href="/public/css/style.css" /> ```  to ```  <link rel="stylesheet" href="/public/css/style.css" />```. The site is broken when that path is not followed

**Comment by IAmSalvaMartini** [comment]
Also, can you please fix the commit names to more accurately represent what they do? Some of the names are not very representative of what is actually being changed in the commit. Please update and get back to me

**Comment by GayanKod** [comment]
Ah okay I will, you mean `<link rel="stylesheet" href="/css/style.css" />` likewise ? 
Okay I'll fix commit names also.
Thank you for your fast review.

**Comment by GayanKod** [comment]
I did the changes and I renamed a commit name meaningfully also. Please review it soon! 
Really appreciate your support!!!
Thank you so much!

**Review by namruthahari — APPROVED** [review]

**Pull request merged**
