### PR TITLE
Create navbar.html

### PR DESCRIPTION
**Pull request by Agasthyan07**
I have created a scrollable navbar for your website, please gothrough it

### CODE REVIEW

**Comment by namruthahari** [comment]
Please do add a screenshot of the navbar @Agasthyan07 !

**Comment by Agasthyan07** [comment]
Screenshot (14)

**Comment by namruthahari** [comment]
Do add the screenshot of the navbar in context to the open sourced project. Add the screenshot of the navbar integrated along with my website and not a separate project. @Agasthyan07

**Comment by IAmSalvaMartini** [comment]
@Agasthyan07 Please update, or this PR will be closed in 48 hours

**Comment by IAmSalvaMartini** [comment]
Closed due to inactivity.

**Pull request closed without merging**
